version: '3.8'

# This file is only for testing.
# See https://github.com/ocvt/docker for prod configuration.

services:
  ocvt-site:
    image: ocvt/ocvt-site:latest
    restart: unless-stopped
    env_file: ocvt-site.env
    ports:
      - 4000:4000
