name: Publish container image on new release
on:
  workflow_dispatch: ~
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/ocvt/ocvt-site:${{ github.event.release.tag_name }}
