name: Publish container image on new release
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          registry: ghcr.io
          repository: ocvt/ocvt-site
          tag_with_ref: true
